build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile
      no_cache: true
      secrets:
        ba_common_git:
          type: env
          value: GIT_COMMON_SSH_KEY